### ISSUE TITLE
The largest resolution of depthmap?

### ISSUE THREAD

**Issue by CC9310** [zzangjinsun/NLSPN_ECCV20#15]
When i testing my private data of depth (768, 1152), while, the cuda run out of memory, can you specify the largest resolution your method can handle?

**Comment by zzangjinsun** [comment]
https://github.com/zzangjinsun/NLSPN_ECCV20/blob/46dfa4c42fc380a1261b4f7175753b897ec9bfb0/src/data/kittidc.py#L239-L247

You can try _--test_crop_ and _--top_crop_ to crop the top area during the testing.
If it's not enough, modification on the code is needed.
