### ISSUE TITLE
Initial Depth Prediction vs Final Depth Prediction

### ISSUE THREAD

**Issue by dronefreak** [zzangjinsun/NLSPN_ECCV20#17]
Hi @zzangjinsun 

I was hoping if you could provide some insights regarding the quantifiable differences between the initial depth prediction (after the Enc-Dec) and the final depth prediction (after SPN and affinity norm), it would be great. Is the initial depth not dense enough? Does it still have invalid values? What is the RMSE that you obtain on the initial depth prediction?
I am currently working on building a real-time solution so it would be nice if you could provide me with some details.
Thanks.

**Comment by zzangjinsun** [comment]
Hi @dronefreak,
For evaluation, you can use _--save_image_ flag to save all the information including the initial prediction.
The initial prediction with no propagation has incorrect values and after iterative propagation those values become correct.

**Comment by dronefreak** [comment]
Thanks for your quick reply. I have an observation that I would like to confirm with you. I have observed that the propagation layer is essentially parameter free, and most of the bulky operations are performed during the encoder-decoder stage. Do you confirm this observation of mine, or am I missing something?

**Comment by zzangjinsun** [comment]
Yes right, all the information for spatial propagation comes from Enc-Dec network except for a small conv layer and a normalization constant (conv_offset_aff and aff_scale_const).

**Comment by dronefreak** [comment]
Thanks a lot!
Closing this now.
