### ISSUE TITLE
question on kitti

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [zzangjinsun/NLSPN_ECCV20#19]
Hi, Park. I run the code in kitti dataset with batch size 12 for 20 epochs on 4 gpus. But the rmse on validation dataset is 781mm. Maybe something is wrong during my training? Could you share me the files saved in the save_dir? Thank you.

**Comment by zzangjinsun** [comment]
I remember that the best result I got was with a batch size 24 on 6 GPUs.
If you want to use the best model, please refer to the released models:
https://github.com/zzangjinsun/NLSPN_ECCV20#pre-trained-models-and-results
