### ISSUE TITLE
Why  are the parameters of `conv_offset_aff ` set to zeros?

### ISSUE THREAD

**Issue by EthanZhangYi** [zzangjinsun/NLSPN_ECCV20#22]
Why  are the parameters of `conv_offset_aff ` initialized to zeros specially in NLSPN? (line 56-57)
https://github.com/zzangjinsun/NLSPN_ECCV20/blob/46dfa4c42fc380a1261b4f7175753b897ec9bfb0/src/model/nlspnmodel.py#L52-L57

**Comment by zzangjinsun** [comment]
Hi @EthanZhangYi. Sorry for the late reply.

With the zero-initialization, offset and affinity values are zero-initialized too.
If you don't want it, please comment those lines out.
