### ISSUE TITLE
effects on hyper-params in training ?

### ISSUE THREAD

**Issue by Wenchao-Du** [zzangjinsun/NLSPN_ECCV20#28]
Hi, i have tried the released model for kitti dc and got the consistent results. But i have some problems on two hyper-params in config file: preserve_input and legacy, i closing any one of them would significant errors compared the ground truth, so i want to know if this two params are opened in training ?  i have tried to retrain your model with closing this two params, but open them during testing , it leads to larger errors. Instead, closing them leads to consistent results with training during testing. Thanks.

**Comment by zzangjinsun** [comment]
For the pre-trained model, you must use --preserve_input and --legacy.
However, if you wanna train your own model, --legacy should not be used but --preserve_input is up to you.
