### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yqq924** [zzangjinsun/NLSPN_ECCV20#31]
Hello, the RAW depth I extracted from NYUv2 contains cavities, so how can it be used as GT

**Comment by zzangjinsun** [comment]
Hello @yqq924 ,

I used the preprocessed NYU dataset of [sparse-to-dense](https://github.com/fangchangma/sparse-to-dense).

Please refer to [here](https://github.com/zzangjinsun/NLSPN_ECCV20#nyu-depth-v2-nyuv2) to download the preprocessed NYU dataset.

**Comment by yqq924** [comment]
Hello, I downloaded the data set according to your instructions, but there are still holes in the depth map, so how can it be used as GT


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzangjinsun/NLSPN_ECCV20"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月17日(星期一) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzangjinsun/NLSPN_ECCV20] dataset (#31)





 
Hello @yqq924 ,
 
I used the preprocessed NYU dataset of sparse-to-dense.
 
Please refer to here to download the preprocessed NYU dataset.

**Comment by zzangjinsun** [comment]
Losses are calculated with only valid pixels. Please refer to the following codes:

L1 loss:
https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/loss/submodule/l1loss.py#L28-L33

L2 loss:
https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/loss/submodule/l2loss.py#L28-L33

Thx!

**Comment by yqq924** [comment]
Ok,I thank I know that, thanks very much.



发自我的iPhone


------------------ Original ------------------
From: Jinsun Park ***@***.***&gt;
Date: Wed,May 19,2021 4:55 PM
To: zzangjinsun/NLSPN_ECCV20 ***@***.***&gt;
Cc: yqq924 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [zzangjinsun/NLSPN_ECCV20] dataset (#31)





 
Losses are calculated with only valid pixels. Please refer to the following codes:
 
L1 loss:
 https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/loss/submodule/l1loss.py#L28-L33
 
L2 loss:
 https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/loss/submodule/l2loss.py#L28-L33
 
Thx!

**Comment by yqq924** [comment]
hi,I’d like to know weather the test dataset have been zoomed to 228*304?thank you thank you!!!!!






------------------ Original ------------------
From: Jinsun Park ***@***.***&gt;
Date: Wed,May 19,2021 4:55 PM
To: zzangjinsun/NLSPN_ECCV20 ***@***.***&gt;
Cc: yqq924 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [zzangjinsun/NLSPN_ECCV20] dataset (#31)





 
Losses are calculated with only valid pixels. Please refer to the following codes:
 
L1 loss:
 https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/loss/submodule/l1loss.py#L28-L33
 
L2 loss:
 https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/loss/submodule/l2loss.py#L28-L33
 
Thx!
