### ISSUE TITLE
Question about the num_sample setting

### ISSUE THREAD

**Issue by Airy00** [zzangjinsun/NLSPN_ECCV20#33]
hello，I'm very glad to learn your code in this project， but there's a hesitation of how to set the num_sample if I want to use all the points in the depth map without sample?

**Comment by zzangjinsun** [comment]
Hi, num_sample=0 will lead to no sampling, so you can use all the input points!

Please refer to:

KITTI:
https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/data/kittidc.py#L257-L258

and

NYU:
https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/data/nyu.py#L157

if you want to use all the points for the NYU, just put a very big number or modify the NYU data loader similarly to KITTI one.

**Comment by Airy00** [comment]
Ok, I'll try it, thank you!
