### ISSUE TITLE
Can't reproduce results

### ISSUE THREAD

**Issue by coledea** [zzangjinsun/NLSPN_ECCV20#34]
Hello,

I've tried to reproduce your results with the KITTI dataset, but the net outputs weird predictions (see image).
I've downloaded the test dataset from KITTI ("test_depth_completion_anonymous"), generated a json and then executed exactly the command you stated.
Have you ever encountered this problem? What could I have done wrong?
![0000000019](https://user-images.githubusercontent.com/69478798/131828188-180af3ad-17d0-4d9e-aea0-b179eba23823.png)

**Comment by zzangjinsun** [comment]
Hello, it looks very weird and I don't have a clear idea about this result.
Did you use the same library version I used? (e.g., apex).

**Comment by coledea** [comment]
Hm, yes maybe it has something to do with library versions. I work on windows, and I wasn't able to install the apex version you stated. I had to install a newer one for the program to run.
