### ISSUE TITLE
How many sparse points are needed for right depth?

### ISSUE THREAD

**Issue by DingYikang** [zzangjinsun/NLSPN_ECCV20#35]
Hi,
Thanks for your nice work. I'm wondering how many sparse points at least are needed for producing right depth? For example, have you tested using 100 sparse points or less? 
Looking forward  to your reply. 
Thank you!

**Comment by zzangjinsun** [comment]
Hello,
For NYUv2 data, I tested with 500 samples.
For KITTI data, I think about 1k points (e.g. the number of points from VLP16 LiDARs) might be needed to obtain reasonable depth maps.
