### ISSUE TITLE
What did you do with the dense depth map in the result

### ISSUE THREAD

**Issue by zura-false** [zzangjinsun/NLSPN_ECCV20#36]
Hello, it's a great honor to refer to your work，I'm making subsequent point cloud processing for your depth completion results，When using the pictures posted in the paper, I can succeed，However, when I use the results you published in result or the results of my own test, I will fail。So I want to know what you did with the depth completion results，thank you。

**Comment by zzangjinsun** [comment]
Sorry I didn't get the point of your question.

I think you may have different input value ranges between images [0, 255] and depth completion results [0, 80~100]?
