### ISSUE TITLE
Can not reproduce the NYU result in paper.

### ISSUE THREAD

**Issue by guangkaixu** [zzangjinsun/NLSPN_ECCV20#37]
Hi, thanks for your great contibution to depth completion.

I followed nearly all your dependencies listed in README.md(except for Ubuntu, my Ubuntu version is 20.04), and downloaded the   NYU dataset from link in README.md. But I can not reproduce the NYU result in paper, my reproduce result is:
```
 Metric   |  RMSE: 0.2249  MAE: 0.1629  iRMSE: 0.0628  iMAE: 0.0356  REL: 0.0646  D^1: 0.9645  D^2: 0.9973  D^3: 0.9997
```
When installing DCN module, I add some ';' cause it raises ERROR. Also, 'DCN.modulated_deform_conv_forward' is replaced by 'DCN.modulated_deform_conv2d_forward' in src.model.modulated_deform_conv_func.py, line 26, following https://github.com/zzangjinsun/NLSPN_ECCV20/issues/3#issuecomment-698204674.

How can I reproduce the result and what should I do?

**Comment by zzangjinsun** [comment]
You don't need to modify DCN module if you use the DCN module included in the repo.

Did you use the following command for the evaluation?

An example command for NYUv2 dataset testing
$ python main.py --dir_data PATH_TO_NYUv2 --data_name NYU  --split_json ../data_json/nyu.json \
    --patch_height 228 --patch_width 304 --gpus 0,1,2,3 --max_depth 10.0 --num_sample 500 \
    --test_only --pretrain ../results/NLSPN_NYU.pt --preserve_input --save NAME_TO_SAVE --legacy

I think you missed some arguments such as --preserve_input or --legacy

**Comment by guangkaixu** [comment]
Oh yeah... I missed both arguments, and now the code works. Thank you so much!
