### ISSUE TITLE
Questions about supervision.

### ISSUE THREAD

**Issue by jikerWRN** [zzangjinsun/NLSPN_ECCV20#39]
Thanks for your good work and open source code!

When I read the paper and code, I have a question. As far as I know, in the CSPN series of papers, the algorithm first obtains an initial depth image, and then it uses iterative spatial propagation to obtain the final depth image. I found that in these algorithms, such as NLSPN, the initial depth map is not supervised. I wonder if joining the  supervision of the initial depth will limit the expressive ability of the network?  And I would like to ask if you have done similar experiments or verified the performance of the initial depth map？

Thanks and looking forward to your reply!

**Comment by zzangjinsun** [comment]
Hi @jikerWRN,
Of course, I tried intermediate supervision on the initial depth when I was working on the NLSPN.
However, I concluded that the intermediate supervision on the initial depth is too strong, and it weakens the role of the propagation part for further improvement.
If you are working on the depth completion, please try and share your experience later!

**Comment by jikerWRN** [comment]
Ok, I just have such a question, and did not conduct related experiments. If I do related experiments later, I will share it through a new issue. Thanks!
