### ISSUE TITLE
Camera Intrinsic

### ISSUE THREAD

**Issue by eugenelyj** [zzangjinsun/NLSPN_ECCV20#41]
Hello, why do you subtract 8.0 and 6.0 from the cx and cy?

https://github.com/zzangjinsun/NLSPN_ECCV20/blob/master/src/data/nyu.py#L74

**Comment by zzangjinsun** [comment]
Hi, because boundaries are cropped as follows:

https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/data/nyu.py#L66-L67

**Comment by eugenelyj** [comment]
Got it. Thanks.
