### ISSUE TITLE
A question about the evaluation on KITTI Depth Completion validation sets?

### ISSUE THREAD

**Issue by prstrive** [zzangjinsun/NLSPN_ECCV20#42]
Is your code tailored for NYU dataset? Some data preprocessing or metrics do not seem to match KITTI's, e.g., "RMSE" in KITTI is in mm and not in meter.

**Comment by zzangjinsun** [comment]
Evaluation metrics results are the same as those obtained from KITTI's evaluation codes.
Please compare the code with the KITTI official devkit.

For KITTI, you just need to multiply 1000 to get mm from m.
