### ISSUE TITLE
A question about the evaluation on pre-trained model on KITTI DC datasets?

### ISSUE THREAD

**Issue by Danica-zc** [zzangjinsun/NLSPN_ECCV20#43]
hello，thanks for sharing the code!
 I downloaded the pre-trained model on KITTI DC datasets from here (https://drive.google.com/file/d/11by_1oglcncSHFeF3S2ldcysQYjyDcQh/view).  After testing, it tells "KeyError:""filename""storage" not found". I think the pre-trained model may be corrupted .

**Comment by zzangjinsun** [comment]
Hi, from my side it works fine.
Please download it again or be sure that you are using python3.

**Comment by Danica-zc** [comment]
yes, I am sure I am using python3.7

**Comment by Danica-zc** [comment]
There are someting wrong still. Is it right?  NLSPN_KITTI_DC.pt   102637kb

**Comment by zzangjinsun** [comment]
Exactly. I even tested with the newest (stable) version of pytorch and apex on anaconda and it worked fine.

**Comment by Danica-zc** [comment]
Did you use the model downloaded from this link ?(https://drive.google.com/file/d/11by_1oglcncSHFeF3S2ldcysQYjyDcQh/view)

**Comment by zzangjinsun** [comment]
Yes, I downloaded it from the released link and tested it on a new computer but it worked fine. If it is available, please try the file on a different computer.

**Comment by Danica-zc** [comment]
python main.py --dir_data PATH_TO_KITTI_DC --data_name KITTIDC --split_json ../data_json/kitti_dc.json \
    --patch_height 240 --patch_width 1216 --gpus 0,1,2,3 --max_depth 90.0 --num_sample 0 \
    --test_only --pretrain ../results/NLSPN_KITTI_DC.pt --preserve_input --save NAME_TO_SAVE --legacy
is it the input of this command, no need to change anything else？
