### ISSUE TITLE
Work with Cuda 11

### ISSUE THREAD

**Issue by s-mostafa-a** [zzangjinsun/NLSPN_ECCV20#44]
Hi I hope you're doing great.
Is there any solution to work with later version of CUDA and its related torch, apex, etc?
I tried to install apex but it seems that it's not working for my gpu.

**Comment by zzangjinsun** [comment]
Hi @s-mostafa-a ,
I am using apex with python 3.8, cuda-11.1, apex 0.1, and pytorch 1.9.1 now and there is no problem.
Which problem do you have?

**Comment by s-mostafa-a** [comment]
Thank you for your reply @zzangjinsun.
I installed the versions you mentioned successfully. But still I have problem installing [DCN](https://github.com/xvjiarui/Deformable-Convolution-V2-PyTorch).

**Comment by s-mostafa-a** [comment]
Never mind. I probably found the solution. 
There is some problem here with the [modified repository of dcn](https://github.com/xvjiarui/Deformable-Convolution-V2-PyTorch).
They have fixed it here in "pytorch_1.0.0" branch of the [original repository of dcn](https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch). (Mainly [this commit](https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/commit/e00498f0250eeaafe0e4c5c089385f826cae55fe))
What I did is:
```
git clone https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch/
cd ./Deformable-Convolution-V2-PyTorch/
git checkout pytorch_1.0.0
sh make.sh
```

**Comment by zura-false** [comment]
Hi, I am also using these configs but I am getting an error when installing apex，I got the error" fatal: Could not parse object '4ef930c1c884fdca5f472ab2ce7cb9b505d26c1a' "by running"git reset --hard 4ef930c1c884fdca5f472ab2ce7cb9b505d26c1a",If I run the next sentence of pip directly，It will prompt the error of the cuda version, have you encountered this situation?

**Comment by zura-false** [comment]
> Hi, I am also using these configs but I am getting an error when installing apex，I got the error" fatal: Could not parse object '4ef930c1c884fdca5f472ab2ce7cb9b505d26c1a' "by running"git reset --hard 4ef930c1c884fdca5f472ab2ce7cb9b505d26c1a",If I run the next sentence of pip directly，It will prompt the error of the cuda version, have you encountered this situation?

I replaced the correct torch version, it can run after skipping this sentence
