### ISSUE TITLE
Just encoder and decoder without refining

### ISSUE THREAD

**Issue by ch5374** [zzangjinsun/NLSPN_ECCV20#45]
Hi,

What is the RMSE using only encoder and decoder that is not refined(propagation)?

I wonder how big the performance improvement that compared to when there was no NLSPN module.

Thank you

**Comment by zzangjinsun** [comment]
Hi, I don't have the exact number for that option currently.
However, you can train a network with this option: _--prop_time 0_

**Comment by ch5374** [comment]
Thank you!
