### ISSUE TITLE
Depth map units for the NYU dataset

### ISSUE THREAD

**Issue by yuyu19970716** [zzangjinsun/NLSPN_ECCV20#47]
Hello, I would like to ask what is the depth value unit of the depth map in the NYU dataset? Is the downloaded depth map the real distance value?

**Comment by zzangjinsun** [comment]
For a saved result image, you should convert to double and divide by 256.0 to get the real depth value in meters.

https://github.com/zzangjinsun/NLSPN_ECCV20/blob/ba33fa5d9ea62ca970026a145ab18fab76d79d4a/src/summary/nlspnsummary.py#L180

**Comment by yuyu19970716** [comment]
Thanks a lot for your answer! But I'm sorry, maybe I didn't make my question clear.
I want to say that I downloaded the NYU dataset with 8 bit depth and I need to get the true depth distance for each pixel point. At this point each pixel of the depth map is stored using 8 bits, which I know is for viewing convenience. I now need to modify the image to a 16-bit depth map. Then get the true depth distance. Now I made these changes:
     img = cv2.imread(L, cv2.IMREAD_GRAYSCALE) (8-bit raw depth map)
     out = np.array(img, dtype=np.uint16)*255 (16-bit depth map)

The data after I changed to 16-bit depth map is like this:
![image](https://user-images.githubusercontent.com/76560812/168217830-6d1150a2-f1b5-49f7-8493-b3b406973031.png)

But I know that what I get this way is not the true depth distance for the indoor dataset. In the KITTI dataset 16-bit depth map/256 can get the real distance in m.
And for the NYU dataset, the 16-bit depth map/256 gets
![image](https://user-images.githubusercontent.com/76560812/168217309-4e3472fa-adc0-458f-8e1f-34e86996d89a.png)
For the 90 in the upper left corner I think it is definitely not the true depth distance of the indoor dataset, because it should be between 0-4m. So I don't know where I am going wrong. Please can you help me with this problem. thank you very much!

The 8-bit raw NYU dataset I downloaded online looks like this:
![image](https://user-images.githubusercontent.com/76560812/168217629-211a5025-ee34-4fd1-87c0-7a06af25b60d.png)

I don't think they are representing real distance information like KITTI. So I want to know if I get the real distance information by changing them to 16 bits by the above method and then dividing by 256. But it seems like I'm not doing anything. It seems unreasonable that I *255 when 8-16 bits, and /256 when it becomes true depth distance.
I am very much looking forward to your reply!

**Comment by zzangjinsun** [comment]
If you are using the hdf5 format dataset, you can use the original value directly for metric depth.
Otherwise, from the original dataset, you should convert pixel value directly to get the real depth value.
Reference: https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html

![image](https://user-images.githubusercontent.com/20081006/171103084-91afcb5f-a9af-48af-b34a-60e62888bdd2.png)

**Comment by Slow-Traveler** [comment]
Have you solved this problem？i have a same one.
