### ISSUE TITLE
Trying to use COLMAP points as input

### ISSUE THREAD

**Issue by andreadalcin** [zzangjinsun/NLSPN_ECCV20#48]
Hello,
I am trying to use points from the COLMAP SfM pipeline as input to the net. Results are unfortunately not consistent with other results I found. 
Is there an "official" way to use those points as input?

**Comment by zzangjinsun** [comment]
I didn't try points from the COLMAP. However, I think you just need to generate a sparse (or semi-dense) depth map from the COLMAP result and then use that image as an input.
