### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by SGXC33** [zzangjinsun/NLSPN_ECCV20#50]
Hello ! When I build and install DCN, I get "RuntimeError: Error compiling objects for extension", how can I solve it?
Of course, I am following these two commands "$ cd NLSPN_ROOT/src/model/deformconv
$ sh make.sh" to create DCN

FAILED: /root/NLSPN_ECCV20-master/src/model/deformconv/build/temp.linux-x86_64-3.9/root/NLSPN_ECCV20-master/src/model/deformconv/src/cuda/deform_conv_cuda.o 

FAILED: /root/NLSPN_ECCV20-master/src/model/deformconv/build/temp.linux-x86_64-3.9/root/NLSPN_ECCV20-master/src/model/deformconv/src/cuda/deform_psroi_pooling_cuda.o 

FAILED: /root/NLSPN_ECCV20-master/src/model/deformconv/build/temp.linux-x86_64-3.9/root/NLSPN_ECCV20-master/src/model/deformconv/src/cuda/modulated_deform_conv_cuda.o 

RuntimeError: Error compiling objects for extension

**Comment by zzangjinsun** [comment]
Not sure about the error but some google search results suggest checking the PyTorch version.
e.g. https://stackoverflow.com/a/74207847
