### ISSUE TITLE
Just multiply confidence and initial depth together while propagating!

### ISSUE THREAD

**Issue by XJTUXYC** [zzangjinsun/NLSPN_ECCV20#52]

**Comment by yudmoe** [comment]
Hi bro, I have the same question about why the confidence should be propagated, the function ModulatedDeformConvFunction looks quite complex, . 
Did you get the result of just  multiply confidence and initial depth?

**Comment by zzangjinsun** [comment]
Hi, you SHOULD NOT multiply confidence directly to depth values because confidence-multiplied affinity values are normalized and the normalized values are multiplied to depth values.
