### ISSUE TITLE
can I compile DCN using cuda version later than 10.2

### ISSUE THREAD

**Issue by scutzetao** [zzangjinsun/NLSPN_ECCV20#53]
Hi I tried to compile the project with a cuda version 11.0 and get an error 
" File "/home/ztchen/Projects/NLSPN_ECCV20/src/model/modulated_deform_conv_func.py", line 13, in <module>
    import DCN
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory"

Is the DCN compilation tied to cuda10.2?

Thanks

**Comment by zzangjinsun** [comment]
Hi.
From my experience, the DCN compilation works with CUDA 11.3
