### ISSUE TITLE
The problem of the loss function

### ISSUE THREAD

**Issue by sunohm** [zzangjinsun/NLSPN_ECCV20#57]
Hello, 
    Thank you for your contribution. I have a question I would like to ask you. Why use a weighted sum of  L1 and L2 loss, 1.0L1+1.0L2?

**Comment by zzangjinsun** [comment]
We empirically found that combining L1 and L2 losses effectively balances RMSE and MAE. It is also helpful to get a better RMSE in the KITTIDC dataset.

The ablation study results in the [supplementary material](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123580120-supp.pdf) are given as follows:

![image](https://github.com/zzangjinsun/NLSPN_ECCV20/assets/20081006/6f12b24e-4c91-43c8-a331-58757f374a30)

Please refer to the supplementary material for more details.
