### ISSUE TITLE
Error in mixed-precision training.

### ISSUE THREAD

**Issue by MurrayC7** [zzangjinsun/NLSPN_ECCV20#7]
Sorry for bothering again, I find opt_level of 'O1' (for mixed-precision training) is unavailable, as the error showed.
```
RuntimeError: "deform_conv_forward_cuda" not implemented for 'Half'
```
In case I'm not accessible to a powerful GPU machine, I wonder if I can use larger batch_size to train under mixed precision, since this code provides the option. Thanks again :)

**Comment by zzangjinsun** [comment]
Although my code framework provides mixed-precision training thx to apex, deform conv module does not provide half-precision training as far as I know. :(

**Comment by MurrayC7** [comment]
Alright, thank you still for your reply. It seems I have to downgrade the patch_size or batch_size at present before a more efficient way is found. Anyway, I prefer your nice work and tidy code.
