### ISSUE TITLE
Request for released model

### ISSUE THREAD

**Issue by youzunzhi** [zzangjinsun/NLSPN_ECCV20#8]
Hi! Thank you for sharing your source code! I wonder if you can also share your trained models of both datasets which achieve the performance in your paper so I can directly run the testing code. Thank you very much!

**Comment by zzangjinsun** [comment]
Unfortunately, after code version up, the pre-trained weights are not directly compatible with the new codes. I will train full-model later because I have a limited number of GPUs now (used for other works now)

**Comment by youzunzhi** [comment]
That's cool. Thanks.

**Comment by JUGGHM** [comment]
> Unfortunately, after code version up, the pre-trained weights are not directly compatible with the new codes. I will train full-model later because I have a limited number of GPUs now (used for other works now)

Seems it's a common confusing problem: code released should be neat, but not the same when good experiment results occur.

**Comment by zzangjinsun** [comment]
@youzunzhi If you don't mind to use a new checkpoint file trained with less number of batch size, I can share that file. It is trained with a small number of image batches for new code verification (slightly worse than the best result). Plz let me know your e-mail.

**Comment by youzunzhi** [comment]
> @youzunzhi If you don't mind to use a new checkpoint file trained with less number of batch size, I can share that file. It is trained with a small number of image batches for new code verification (slightly worse than the best result). Plz let me know your e-mail.

Thank you so much! It's youzunzhi@gmail.com

**Comment by zzangjinsun** [comment]
Please check the e-mail. Thx!!

**Comment by imransai** [comment]
Hi Jinsun, Would you mind to send me the model trained with less batch sizes? Really appreciate it! My email id is saifimran06@gmail.com.

**Comment by rpautrat** [comment]
Hi Jinsun,

Thank you for the nice work and for sharing the code. I am also interested in your model trained with smaller batch sizes, as I am not sure to be able to wait that you release the bigger model. My email address is [remi.pautrat@gmail.com](remi.pautrat@gmail.com). Thank you very much!!

**Comment by zzangjinsun** [comment]
I already released pre-trained models. Please refer to the https://github.com/zzangjinsun/NLSPN_ECCV20#pre-trained-models-and-results

**Comment by rpautrat** [comment]
Great, sorry for missing that! Thanks a lot for sharing them!
