### ISSUE TITLE
regarding cuda 10.2

### ISSUE THREAD

**Issue by imransai** [zzangjinsun/NLSPN_ECCV20#9]
Hi Jinsun,
Just wanted to get some more info, about how important it is to install cuda 10.2 to able to install the deformable cnn bindings. Looks like the cuda 10.2 is supported in ubuntu >= 18.04, (if i am not mistaken). Is it possible to give support for cuda 10.1?

**Comment by zzangjinsun** [comment]
I think it should work with 10.1 without any problems.
(I remember that at the early stage of this work I used a GPU server with CUDA 9 with ubuntu 14.04.)

For the pre-trained models, I am trying to make checkpoint files be compatible with the current version of codes (there were many requests these days haha!)

Please give me a few days and I will upload them on the git.
Thank you!
